# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - master
  - dev

pool:
  vmImage: 'ubuntu-latest' # examples of other options: 'macOS-10.15', 'vs2017-win2016'

variables:
  IS_AZURE_PIPELINES: true
  NODE_ENV: 'test'
  DB_DATABASE: 'test-database'
  DB_USER: 'user'
  DB_PASSWORD: 'password'

steps:
- task: AzureMysqlDeployment@1
  inputs:
    ConnectedServiceName: # Or alias azureSubscription
    DatabaseName: test-database
    SqlUsername: user
    SqlPassword: password

- task: NodeTool@0
  inputs:
    versionSpec: '12.x' # replace this value with the version that you need for your project

- script: npm install
  displayName: 'Install dependencies'

- script: npm run test:e2e
  displayName: 'E2E tests'

- script: npm run test:cov
  displayName: 'Test coverage'
