# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - master
  - dev

pool:
  vmImage: 'ubuntu-latest' # examples of other options: 'macOS-10.15', 'vs2017-win2016'

variables:
  IS_AZURE_PIPELINES: true
  NODE_ENV: 'test'
  DB_DATABASE: 'test_database'
  DB_USER: 'root'
  DB_PASSWORD: 'root'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x' # replace this value with the version that you need for your project

- script: |
    mysql --version
  displayName: 'MySQL Version'

- script: |
    sudo /etc/init.d/mysql start
  displayName: 'Start MySQL Server'

- script: |
    sudo mysql -uroot -proot -e "set global sql_mode='';"
    sudo mysql -uroot -proot -e "create database test_database;"
  displayName: 'Create databases'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run typeorm migration:run
  displayName: 'Run migrations'

- script: npm run test:e2e
  displayName: 'E2E tests'

- script: npm run test:cov
  displayName: 'Test coverage'
